spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/enova
    username: postgres
    password: mounir123
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update


enova:
  app:
    jwtSecret: "enovaenovaenovaenovaenovaenovaenovaenovaenovaenovaenovaenovaenov"
    jwtExpirationMs: 86400000
